### ISSUE TITLE
'Go to definition' not working on allure methods

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure-mocha#27]
When I tries to use Go to definition on allure methods like feature or story Visual Studio Code show ' No definition found'. I use global allure or import it using Nodejs require('mocha-allure-reporter') or es6 import.

I have checked your 'Mocha allure example' and in file webdriver-io.spec.js you use webdriverio. Using go to definition on webdriverio methods moves me to library file like it should.

Why it not work in allure mocha reporter ?

**Comment by just-boris** [comment]
I tried to navigate through webdriver.io method and it doesn't give me any definition as well.

<img width="618" alt="screen shot 2017-04-16 at 11 00 08 pm" src="https://cloud.githubusercontent.com/assets/812240/25074332/b99fd78e-22f8-11e7-9d6a-6726b8c3f35f.png">

Basically it is caused by dynamic Javascript nature, where actual methods can be figured out only in run-time.

Could you tell us what exactly do you want to achieve with this? If you are looking for list of available methods, it is [right here](https://github.com/allure-framework/allure-mocha#runtime-api) in the Readme.

**Comment by netmajor** [comment]
I had in mind 'webdriverio' module. My bad !

My goal is to navigate to definitions of the methods in the allure reporter for mocha. When I open index.js file in mocha-allure-reporter folder in node_modules I can not find methods from Readme :/
