### ISSUE TITLE
Is there a way to add Request and Response with Allure report for API mocha tests?

### ISSUE THREAD

**Issue by AartiJ** [allure-framework/allure-mocha#43]

**Comment by just-boris** [comment]
Using globally available `allure.createAttachement` you can attach any data, including Request/Response content.

**Comment by AartiJ** [comment]
Thank you. I was able to get that working

**Comment by just-boris** [comment]
Yes, you will need to convert to string on your side. We take your value and pass it to the `fs.writeFile` as it is. That's why you will have to convert it to string.

**Comment by AartiJ** [comment]
so no way to get content as JSON?

**Comment by baev** [comment]
In order to save attachment you need to convert your data to string, and then pass it to `createAttachement` method. This way you have much more control over attachment content - for example you may want to prettify json before attaching. In case you know media type of attachment content - you can provide it to Allure as well (Allure have different views for different attachment types).
