### ISSUE TITLE
Hook's name is displayed incorrectly if data was uploaded on allure server

### ISSUE THREAD

**Issue by inikolaeva** [allure-framework/allure-mocha#63]
If I upload data on allure server, "Unkown" is displayed in launch for hooks (hook has his own name).
I expect to see hook name instead of "Unkown" 
![image](https://user-images.githubusercontent.com/42569414/88175884-24bb3800-cc2f-11ea-8c31-4e8e5f2105cc.png)
![image](https://user-images.githubusercontent.com/42569414/88174144-731b0780-cc2c-11ea-8aee-ffecd2efc955.png)

local report even don't have hook's name:
![image](https://user-images.githubusercontent.com/42569414/88173631-91ccce80-cc2b-11ea-8c43-e2028a6d256b.png)

But for me the most important case is displaying after uploading to allure server

**Comment by just-boris** [comment]
Server questions go to @baev or @sseliverstov

**Comment by aposiker** [comment]
I faced a similar issue, and looks like the root cause of this is that steps from Mocha hooks (before... or after...)  have no "name" in .json files in allure-results even if the name was passed as a parameter to hook. To reproduce the issue you can use the next repo - https://github.com/aposiker/simplifiedAPITests just run the tests and check allure-results files and you'll see something like this
![image](https://user-images.githubusercontent.com/17815118/142609580-7c3432ab-c8a3-4890-8fcd-56a4cfb24e1e.png)

**Comment by baev** [comment]
https://github.com/allure-framework/allure-js/pull/410/
